global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-backend'
    static_configs:
      - targets: ['192.168.122.13:8000']

  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - '192.168.122.11:9100'
          - '192.168.122.12:9100'
          - '192.168.122.13:9100'
          - '192.168.122.14:9100'
          - '192.168.122.15:9100'
        labels:
          group: 'vm-nodes'
